version: '3.9'

services:
  storageproductconnector:
    build: 
      context: ./StorageProductConnector
      dockerfile: Dockerfile

    networks:
      - app-network

  ocelotgateway:
    build: 
      context: ./OcelotGateway
      dockerfile: Dockerfile
    ports:
      - "8083:8086"
    networks:
      - app-network

  aspnetseminar3:
    build: 
      context: ./ASP.NET_Seminar_3
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge