version: '3.9'

services:
  storageproductconnector:
    build: 
      context: ./StorageProductConnector
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - app-network

  ocelotgateway:
    build: 
      context: ./OcelotGateway
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      - app-network

  aspnetseminar3:
    build: 
      context: ./ASP.NET_Seminar_3
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge